namespace Chewy
{
    struct ChewyNode
    {
        UInt64 Magic;
    };

    struct ChewyLayout
    {
        UInt32 Order;
        Windows.Foundation.Size Size;
        Windows.Foundation.Point Location;
    };

    [default_interface]
    runtimeclass ChewyStyle
    {
        ChewyStyle(String style);
    }

    [default_interface]
    runtimeclass ChewyTaffy
    {
        ChewyTaffy();

        ChewyNode NewLeaf(ChewyStyle style);
        void SetChildren(ChewyNode node, Windows.Foundation.Collections.IVectorView<ChewyNode> children);
        void ComputeLayout(ChewyNode rootNode, Int32 width, Int32 height);
        ChewyLayout GetLayout(ChewyNode node);
    }
}